### ISSUE TITLE
Redirection target for suffixpassthrough = false in ID resolution service

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biscicol-fims#10]
When suffixpassthrough is false and a redirection target is specified we need to forward to the URL specified in the dcterms:hasVersion metadata element.

For example, in:

http://www.biscicol.org/id/ark:/21547/ALa2

Need to redirect here:
https://amphibiandisease.org/project.php?id=fb8f92cead24438d09aa5af67c70d17c

**Comment by rodney757** [comment]
hmm, so anytime a user resolves a dataset, they will be redirected to the
data? The only time we show the metadata for the dataset (with the download
links for excel, txt, n3) is when someone visits the /id/metadata service?

Another issue is that in the metadata service, if the bcid is a dataset, we
have the excel, txt, and n3 download links. However it appears that
amphibiandisease is minting datasets, but not uploading the data. So maybe
if graph == null, then we don't have the download links?

**Comment by rodney757** [comment]
Another problem I see, especially with uploaded datasets via FIMS, is
exposing private datasets forwarding to the webAddress. Thoughts?

**Comment by jdeck88** [comment]
Here is how i see handling resolution:

http://fims.readthedocs.org/en/latest/identifiers.html#bcid-resolution-system

For private datasets i think we should still publish the metadata but for
the links, insert something that says:

"This is listed as a private dataset, You must be logged in to download
data"

I don't see any issue with forwarding requests to target urls for private
sets.... i'm assuming they would not bother publishing the GUID if it was
an issue OR they can control privacy on the final target.

John

On Mon, Feb 29, 2016 at 3:47 PM, RJ Ewing notifications@github.com wrote:

> Another problem I see, especially with uploaded datasets via FIMS, is
> exposing private datasets forwarding to the webAddress. Thoughts?
> 
> On Tue, Mar 1, 2016 at 7:25 AM, Rj Ewing ewing.rj@gmail.com wrote:
> 
> > hmm, so anytime a user resolves a dataset, they will be redirected to the
> > data? The only time we show the metadata for the dataset (with the
> > download
> > links for excel, txt, n3) is when someone visits the /id/metadata
> > service?
> > 
> > Another issue is that in the metadata service, if the bcid is a dataset,
> > we have the excel, txt, and n3 download links. However it appears that
> > amphibiandisease is minting datasets, but not uploading the data. So
> > maybe
> > if graph == null, then we don't have the download links?
> > 
> > On Mon, Feb 29, 2016 at 10:54 PM, John Deck notifications@github.com
> > wrote:
> > 
> > > Assigned #10 https://github.com/biocodellc/biscicol-fims/issues/10 to
> > > @rodney757 https://github.com/rodney757.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/biocodellc/biscicol-fims/issues/10#event-571222395
> > > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biocodellc/biscicol-fims/issues/10#issuecomment-190453424
> .

## 

John Deck
(541) 914-4739

**Comment by rodney757** [comment]
okay, I think everything is working as shown http://fims.readthedocs.org/en/latest/identifiers.html#bcid-resolution-system.

The only difference is for the 2 lines in the table where suffixPassThrough = true && redirectionTarget != null (graph == null OR graph != null) we are only redirecting if there is a suffix. If you want this to redirect everytime (suffix or not), let me know.

**Comment by jdeck88** [comment]
Yes, that is the correct behavior.  The reason is that the root resource of
a suffixpassthrough ID would likely never be resolvable... it would be,
"show me the theoretical concept that stands for the set of all 'things'
that can be resolved using suffixes under this resource"... I haven't found
anyone wanting a web page for that set of things, so instead opt to display
metadata.

On Tue, Mar 1, 2016 at 3:05 PM, RJ Ewing notifications@github.com wrote:

> okay, I think everything is working as shown
> http://fims.readthedocs.org/en/latest/identifiers.html#bcid-resolution-system
> .
> 
> The only difference is for the 2 lines in the table where
> suffixPassThrough = true && redirectionTarget != null (graph == null OR
> graph != null) we are only redirecting if there is a suffix. If you want
> this to redirect everytime (suffix or not), let me know.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biocodellc/biscicol-fims/issues/10#issuecomment-190954012
> .

## 

John Deck
(541) 914-4739
