### ISSUE TITLE
option to show public projects when user is logged in

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biscicol-fims#12]
Put a check-box near the template & query project list drop-down to show public projects or not. 
by default have this box not checked so the only projects that are shown are the projects that a user
belongs to.  It is somewhat confusing for a logged in user to see a long list of public projects (typically).

**Comment by jdeck88** [comment]
Also a checkbox in the validation/upload portion where project is chosen

**Comment by rodney757** [comment]
okay this is implemented in the develop branch. To test this out, pull down the changes from biscicol-fims and biocode-fims-commons.

call "git checkout develop" for each repo.

then build and deploy.

You need to change the following in your biscicol-fims.props files:
resolverMetadataPrefix = http://localhost:8080/lookup/metadata/

**Comment by jdeck88** [comment]
Tested this out and is merged into master branch... works well.
