### ISSUE TITLE
Project chooser in template config fails w/ NULL project configuration

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biscicol-fims#17]
Create a project with a NULL configuration file.  
Goto template creator and choose some other public project and load fields.
Then, choose the project w/ the NULL config.  
What comes back is a Loading message and the old fields all stay there.
Expected result is wipe all the old fields and then display a message that says "No project configuration file found".

(BTW, we should test this case for validate/load data as well)

**Comment by rodney757** [comment]
fixed in commit 5ee2b321fb9620567c7d02a76948861ce9cd8ab9
