### ISSUE TITLE
Overview map sample ID

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biscicol-fims#2]
The overview map uses the first column as the "Sample ID" but it should be the unique key field specified in the configuration file.    See, for example, the attached indopacific template. it shows sampleID: Arthropoda, but it should be "1"

**Comment by jdeck88** [comment]
[indoPacificTemplate.xlsx](https://github.com/biocodellc/biscicol-fims/files/119914/indoPacificTemplate.xlsx)

**Comment by rodney757** [comment]
Fixed with commit ff51d00828d9a647029b499350625d31dd142cd8
