### ISSUE TITLE
Fix link text on expeditionManager page

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biscicol-fims#22]
I see the expedition manager under ARMS... nice.  
however, i noticed all the IDS are shown as:

ark:/21547/R2 and link to http://biscicol.org/n2t.net/ark:/21547/R2

We should display the link as http://n2t.net/ark:/21547/R2 and link to the same.

Also, we should change all links that are shown to use the full http://n2t.net/... text...

**Comment by rodney757** [comment]
fixed in commit fc4f67cb0ff7ecbd9ff13202b65c7ab6cabad594
