### ISSUE TITLE
Project Query REST "tab" service not working correctly

### ISSUE THREAD

**Issue by MikeTrizna** [biocodellc/biscicol-fims#28]
First of all, I want to say how much I love the new Swagger documentation of the FIMS REST API, and a lot of the new features such as the ability to page and limit results. This is going to really help a lot going forward.

I was also really excited to see the new [`/projects/query/tab` endpoint](http://biscicol.org/apidocs/v1.1/#!/Resources/queryTab), because tsv data is my preferred data format. However, I've notice 2 issues with this endpoint:

1. The Swagger documentation is set with "Response Content Type" as "application/json", so all of my sample queries on the documentation page return `"error": "no response from server"`.
2. When using the endpoint with no Response Content Type header, the response gives a **comma**-separated response. Here's a gist showing this behavior, in case I'm doing something incorrectly: [https://gist.github.com/MikeTrizna/531b09ad07832fbd46861b16ae59afe7](https://gist.github.com/MikeTrizna/531b09ad07832fbd46861b16ae59afe7)

I hope this helps!

**Comment by rodney757** [comment]
Thanks for the issue. They are fixed now
