### ISSUE TITLE
ID lookup service Server Error

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biscicol-fims#3]
There is an error on the ID Lookup services... 
"210982 [qtp1045084778-13] WARN  biocode.fims.rest.FimsExceptionMapper  - NullPointerException thrown while retrieving mediaType in FimsExceptionMapper.java"

**Comment by rodney757** [comment]
fixed with commit 593a717ab637cc7689c2e6bbb2cf5f13a759ef1b
