### ISSUE TITLE
Create Better JSON response for validation

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biscicol-fims#5]
The current JSON response mechanism for validation is not really JSON--- its just HTML wrapped in a single element.  To better interface w/ applications calling just the validation mechanism, we want a better response mechanism so it can be interpreted by other applications:

{
  "success": false,
  "warnings": {
      "missingColumns": ["column1"],
      "missingValues": ["column4"]
  },
  "errors": {
      "missingColumns": ["column8"],
      "missingValues": ["column2", "column3"]
  }
}

where column1, column2, etc.. . are the actual column names.  For the biscicol fims we want to put in the names of the columns as defined by XML configuration file.    

In biscicol fims we want the response output ultimately to look like the current response output.  

Since nobody else is calling this REST service we can change the response mechanism without having to coordinate with other groups.

**Comment by rodney757** [comment]
okay, after looking into this a bit, it's not as straight forward as I first thought. The problem is that every rule has a different message. I'm not sure if we would like to have the ability to customized the warning and error strings for different fims-projects. If not, it would be fairly straightforward. As an example, the warnings object would look like:

"warnings": {
  "groupMessage1": ["message1", "message2"],
  "groupMessage2": ["message1"]
}

where "message1", etc is the message param for the RowMessage java object.

It gets a bit trickier if we would like to have the ability to customize the messages for different fims-projects. for missingColums, missingValues, etc it would be simple. Where it gets more complicated is when the messages currently look like:

Illegal values! minimumDepthInMeters = 900 while maximumDepthInMeters = -110,
Row 4: "ChordataISWrong" not an approved "phylum",
"materialSampleID" column is defined as unique but some values used more than once: 6

Thoughts?

**Comment by jdeck88** [comment]
In plane to sfo, more when I land:  What about
Warnings:
   [{"message":"some msg","group":"some group"}]
Then leave the sorting to the clients.

Also,  all rules are common and only belong in Fims-commons

## 

John Deck
(541) 914-4739

**Comment by rodney757** [comment]
I think it would make our js easier to have the messages sorted by groupMessage. Especially since this is already done in the current Java code.  But either way works, lmk

**Comment by jdeck88** [comment]
Sure, thats fine... i was just looking for a way where all of the messages
could be handled by the same JSON format.   Actually, how are the following
messages different?  and can they be handled by the first JSON syntax you
sent?

Illegal values! minimumDepthInMeters = 900 while maximumDepthInMeters =
-110,
Row 4: "ChordataISWrong" not an approved "phylum",
"materialSampleID" column is defined as unique but some values used more
than once: 6

John

On Tue, Feb 16, 2016 at 3:13 PM, RJ Ewing notifications@github.com wrote:

> I think it would make our js easier to have the messages sorted by
> groupMessage. Especially since this is already done in the current Java
> code. But either way works, lmk
> 
> > On Feb 16, 2016, at 9:52 PM, John Deck notifications@github.com wrote:
> > 
> > In plane to sfo, more when I land: What about
> > Warnings:
> > [{"message":"some msg","group":"some group"}]
> > Then leave the sorting to the clients.
> > 
> > Also, all rules are common and only belong in Fims-commons
> > 
> > ## 
> > 
> > John Deck
> > (541) 914-4739
> > 
> > > On Feb 15, 2016, at 1:30 PM, RJ Ewing notifications@github.com
> > > wrote:
> > > 
> > > okay, after looking into this a bit, it's not as straight forward as I
> > > first thought. The problem is that every rule has a different message. I'm
> > > not sure if we would like to have the ability to customized the warning and
> > > error strings for different fims-projects. If not, it would be fairly
> > > straightforward. As an example, the warnings object would look like:
> > > 
> > > "warnings": {
> > > "groupMessage1": ["message1", "message2"],
> > > "groupMessage2": ["message1"]
> > > }
> > > 
> > > where "message1", etc is the message param for the RowMessage java
> > > object.
> > > 
> > > It gets a bit trickier if we would like to have the ability to
> > > customize the messages for different fims-projects. for missingColums,
> > > missingValues, etc it would be simple. Where it gets more complicated is
> > > when the messages currently look like:
> > > 
> > > Illegal values! minimumDepthInMeters = 900 while maximumDepthInMeters
> > > = -110,
> > > Row 4: "ChordataISWrong" not an approved "phylum",
> > > "materialSampleID" column is defined as unique but some values used
> > > more than once: 6
> > > 
> > > Thoughts?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biocodellc/biscicol-fims/issues/5#issuecomment-184914997
> .

## 

John Deck
(541) 914-4739

**Comment by rodney757** [comment]
Those example include more than just a simple column name. They contain
multiple column names and/or column values, thus making it difficult to
have a response like:

"groupMessage":["column1", "column2"]

If we go with the following response (just realized that the "warnings"
value in my previous reply was an object, when it should have been an
array):

"warnings": [
"groupMessage1": ["message1", "message2"],
"groupMessage2": ["message1"]
]

The end user just needs to iterate through the warnings value, which will
give them the groupMessage, then iterate through each groupMessage to get
the message. This is easy to handle with an unknown number of groupMessages
and messages.

**Comment by jdeck88** [comment]
sounds good.
John

On Tue, Feb 16, 2016 at 3:33 PM, RJ Ewing notifications@github.com wrote:

> Those example include more than just a simple column name. They contain
> multiple column names and/or column values, thus making it difficult to
> have a response like:
> 
> "groupMessage":["column1", "column2"]
> 
> If we go with the following response (just realized that the "warnings"
> value in my previous reply was an object, when it should have been an
> array):
> 
> "warnings": [
> "groupMessage1": ["message1", "message2"],
> "groupMessage2": ["message1"]
> ]
> 
> The end user just needs to iterate through the warnings value, which will
> give them the groupMessage, then iterate through each groupMessage to get
> the message. This is easy to handle with an unknown number of groupMessages
> and messages.
> 
> On Wed, Feb 17, 2016 at 7:24 AM, John Deck notifications@github.com
> wrote:
> 
> > Sure, thats fine... i was just looking for a way where all of the
> > messages
> > could be handled by the same JSON format. Actually, how are the following
> > messages different? and can they be handled by the first JSON syntax you
> > sent?
> > 
> > Illegal values! minimumDepthInMeters = 900 while maximumDepthInMeters =
> > -110,
> > Row 4: "ChordataISWrong" not an approved "phylum",
> > "materialSampleID" column is defined as unique but some values used more
> > than once: 6
> > 
> > John
> > 
> > On Tue, Feb 16, 2016 at 3:13 PM, RJ Ewing notifications@github.com
> > wrote:
> > 
> > > I think it would make our js easier to have the messages sorted by
> > > groupMessage. Especially since this is already done in the current Java
> > > code. But either way works, lmk
> > > 
> > > > On Feb 16, 2016, at 9:52 PM, John Deck notifications@github.com
> > > > wrote:
> > > > 
> > > > In plane to sfo, more when I land: What about
> > > > Warnings:
> > > > [{"message":"some msg","group":"some group"}]
> > > > Then leave the sorting to the clients.
> > > > 
> > > > Also, all rules are common and only belong in Fims-commons
> > > > 
> > > > ## 
> > > > 
> > > > John Deck
> > > > (541) 914-4739
> > > > 
> > > > > On Feb 15, 2016, at 1:30 PM, RJ Ewing notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > okay, after looking into this a bit, it's not as straight forward
> > > > > as
> > > > > I
> > > > > first thought. The problem is that every rule has a different message.
> > > > > I'm
> > > > > not sure if we would like to have the ability to customized the warning
> > > > > and
> > > > > error strings for different fims-projects. If not, it would be fairly
> > > > > straightforward. As an example, the warnings object would look like:
> > > > > 
> > > > > "warnings": {
> > > > > "groupMessage1": ["message1", "message2"],
> > > > > "groupMessage2": ["message1"]
> > > > > }
> > > > > 
> > > > > where "message1", etc is the message param for the RowMessage java
> > > > > object.
> > > > > 
> > > > > It gets a bit trickier if we would like to have the ability to
> > > > > customize the messages for different fims-projects. for missingColums,
> > > > > missingValues, etc it would be simple. Where it gets more complicated
> > > > > is
> > > > > when the messages currently look like:
> > > > > 
> > > > > Illegal values! minimumDepthInMeters = 900 while
> > > > > maximumDepthInMeters
> > > > > = -110,
> > > > > Row 4: "ChordataISWrong" not an approved "phylum",
> > > > > "materialSampleID" column is defined as unique but some values used
> > > > > more than once: 6
> > > > > 
> > > > > Thoughts?
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/biocodellc/biscicol-fims/issues/5#issuecomment-184914997
> > 
> > > .
> > 
> > ## 
> > 
> > John Deck
> > (541) 914-4739
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/biocodellc/biscicol-fims/issues/5#issuecomment-184918052
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biocodellc/biscicol-fims/issues/5#issuecomment-184919704
> .

## 

John Deck
(541) 914-4739

**Comment by rodney757** [comment]
one more thing. Currently we separate messages by worksheet (ex. Validation
results on "Samples" worksheet.) followed by the errors/warnings. I assume
we want to keep this functionality. The response would look like:

[
    "worksheet1": {
        "warnings": [
            "groupMessage1": ["message1", "message2"],
            "groupMessage2": ["message1"]
        ], "errors": ...
    },
    "worksheet2": {
       "warnings": [
            "groupMessage1": ["message1", "message2"],
            "groupMessage2": ["message1"]
        ], "errors": ...
    }
]

**Comment by jdeck88** [comment]
yes.
John

On Fri, Feb 19, 2016 at 6:46 PM, RJ Ewing notifications@github.com wrote:

> one more thing. Currently we separate messages by worksheet (ex. Validation
> results on "Samples" worksheet.) followed by the errors/warnings. I assume
> we want to keep this functionality. The response would look like:
> 
> [
> "worksheet1": {
> "warnings": [
> "groupMessage1": ["message1", "message2"],
> "groupMessage2": ["message1"]
> ], "errors": ...
> },
> "worksheet2": {
> "warnings": [
> "groupMessage1": ["message1", "message2"],
> "groupMessage2": ["message1"]
> ], "errors": ...
> }
> ]
> 
> On Wed, Feb 17, 2016 at 1:46 PM, John Deck notifications@github.com
> wrote:
> 
> > sounds good.
> > John
> > 
> > On Tue, Feb 16, 2016 at 3:33 PM, RJ Ewing notifications@github.com
> > wrote:
> > 
> > > Those example include more than just a simple column name. They contain
> > > multiple column names and/or column values, thus making it difficult to
> > > have a response like:
> > > 
> > > "groupMessage":["column1", "column2"]
> > > 
> > > If we go with the following response (just realized that the "warnings"
> > > value in my previous reply was an object, when it should have been an
> > > array):
> > > 
> > > "warnings": [
> > > "groupMessage1": ["message1", "message2"],
> > > "groupMessage2": ["message1"]
> > > ]
> > > 
> > > The end user just needs to iterate through the warnings value, which
> > > will
> > > give them the groupMessage, then iterate through each groupMessage to
> > > get
> > > the message. This is easy to handle with an unknown number of
> > > groupMessages
> > > and messages.
> > > 
> > > On Wed, Feb 17, 2016 at 7:24 AM, John Deck notifications@github.com
> > > wrote:
> > > 
> > > > Sure, thats fine... i was just looking for a way where all of the
> > > > messages
> > > > could be handled by the same JSON format. Actually, how are the
> > > > following
> > > > messages different? and can they be handled by the first JSON syntax
> > > > you
> > > > sent?
> > > > 
> > > > Illegal values! minimumDepthInMeters = 900 while
> > > > maximumDepthInMeters =
> > > > -110,
> > > > Row 4: "ChordataISWrong" not an approved "phylum",
> > > > "materialSampleID" column is defined as unique but some values used
> > > > more
> > > > than once: 6
> > > > 
> > > > John
> > > > 
> > > > On Tue, Feb 16, 2016 at 3:13 PM, RJ Ewing notifications@github.com
> > > > wrote:
> > > > 
> > > > > I think it would make our js easier to have the messages sorted by
> > > > > groupMessage. Especially since this is already done in the current
> > > > > Java
> > > > > code. But either way works, lmk
> > > > > 
> > > > > > On Feb 16, 2016, at 9:52 PM, John Deck <notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > > In plane to sfo, more when I land: What about
> > > > > > Warnings:
> > > > > > [{"message":"some msg","group":"some group"}]
> > > > > > Then leave the sorting to the clients.
> > > > > > 
> > > > > > Also, all rules are common and only belong in Fims-commons
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > John Deck
> > > > > > (541) 914-4739
> > > > > > 
> > > > > > > On Feb 15, 2016, at 1:30 PM, RJ Ewing <
> > > > > > > notifications@github.com>
> > > > > > > wrote:
> > > > > > > 
> > > > > > > okay, after looking into this a bit, it's not as straight
> > > > > > > forward
> > > > > > > as
> > > > > > > I
> > > > > > > first thought. The problem is that every rule has a different
> > > > > > > message.
> > > > > > > I'm
> > > > > > > not sure if we would like to have the ability to customized the
> > > > > > > warning
> > > > > > > and
> > > > > > > error strings for different fims-projects. If not, it would be
> > > > > > > fairly
> > > > > > > straightforward. As an example, the warnings object would look
> > > > > > > like:
> > > > > > > 
> > > > > > > "warnings": {
> > > > > > > "groupMessage1": ["message1", "message2"],
> > > > > > > "groupMessage2": ["message1"]
> > > > > > > }
> > > > > > > 
> > > > > > > where "message1", etc is the message param for the RowMessage
> > > > > > > java
> > > > > > > object.
> > > > > > > 
> > > > > > > It gets a bit trickier if we would like to have the ability to
> > > > > > > customize the messages for different fims-projects. for
> > > > > > > missingColums,
> > > > > > > missingValues, etc it would be simple. Where it gets more
> > > > > > > complicated
> > > > > > > is
> > > > > > > when the messages currently look like:
> > > > > > > 
> > > > > > > Illegal values! minimumDepthInMeters = 900 while
> > > > > > > maximumDepthInMeters
> > > > > > > = -110,
> > > > > > > Row 4: "ChordataISWrong" not an approved "phylum",
> > > > > > > "materialSampleID" column is defined as unique but some values
> > > > > > > used
> > > > > > > more than once: 6
> > > > > > > 
> > > > > > > Thoughts?
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub.
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > 
> > https://github.com/biocodellc/biscicol-fims/issues/5#issuecomment-184914997
> > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > John Deck
> > > > (541) 914-4739
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/biocodellc/biscicol-fims/issues/5#issuecomment-184918052
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/biocodellc/biscicol-fims/issues/5#issuecomment-184919704
> > 
> > > .
> > 
> > ## 
> > 
> > John Deck
> > (541) 914-4739
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/biocodellc/biscicol-fims/issues/5#issuecomment-185037694
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biocodellc/biscicol-fims/issues/5#issuecomment-186493575
> .

## 

John Deck
(541) 914-4739

**Comment by rodney757** [comment]
Okay, this is implemented in commit fa2f93df36d778e42640950841820d432c7b81ab
