### ISSUE TITLE
Identifier lookups broken

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biscicol-fims#7]
Using the Lookup tool at http://biscicol.org/lookup.jsp  with the example provided gives a server error.
There is a 404 error... i haven't had time to explore this yet but seems like a stale pointer to an old service address?

**Comment by rodney757** [comment]
I think the problem is the resolverMetadataPrefix setting. It should be http://www.biscicol.org/id/metadata/

**Comment by jdeck88** [comment]
ok-- that was one issue, and everything works, EXCEPT the sample on the
page... just use the example in the text box that appears when you load the
page and press the submit button.

John

On Thu, Feb 11, 2016 at 6:38 PM, RJ Ewing notifications@github.com wrote:

> I think the problem is the resolverMetadataPrefix setting. It should be
> http://www.biscicol.org/id/metadata/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biocodellc/biscicol-fims/issues/7#issuecomment-183153637
> .

## 

John Deck
(541) 914-4739

**Comment by jdeck88** [comment]
Oh, and one other issue... when linking from the the CDLIB site, what gets
returned is JSON where it should be the metadata page:

E.g. look at a FIMS ID at CDL:
http://ezid.cdlib.org/id/ark:/21547/AJQ2

then you can click the link that feeds to BiSciCol:

http://www.biscicol.org/id/ark:/21547/AJQ2

And it returns JSON.  IF you extract the address returned in the JSON it is
a bit better:

http://www.biscicol.org/id/metadata/ark:/21547/AJQ2

But... it doesn't give you styling.  However, if you use the key/value
method of calling it:

http://www.biscicol.org/lookup.jsp?id=ark:/21547/AJQ2

it gives the correct view.

So, the ideal situation would be to have
http://www.biscicol.org/id/ark:/21547/AJQ2 return the correct view from the
start.  Possible?

On Thu, Feb 11, 2016 at 9:10 PM, John Deck jdeck88@gmail.com wrote:

> ok-- that was one issue, and everything works, EXCEPT the sample on the
> page... just use the example in the text box that appears when you load the
> page and press the submit button.
> 
> John
> 
> On Thu, Feb 11, 2016 at 6:38 PM, RJ Ewing notifications@github.com
> wrote:
> 
> > I think the problem is the resolverMetadataPrefix setting. It should be
> > http://www.biscicol.org/id/metadata/
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/biocodellc/biscicol-fims/issues/7#issuecomment-183153637
> > .
> 
> ## 
> 
> John Deck
> (541) 914-4739

## 

John Deck
(541) 914-4739

**Comment by rodney757** [comment]
Hmm, when I lookup ark:/21547/R2MBIO56 I get redirected to http://biocode.berkeley.edu/specimens/MBIO56.

Is that not correct?

**Comment by rodney757** [comment]
I believe this is because we have the ResovlerService and the
ResolverMetadataService. As well as those urls are the REST services vs the
jsp pages.

I think it would work to consolidate the services and have one service that
either returned the metadata or redirected the user to the speciman page.
In that case, http://www.biscicol.org/id/ark:/21547/AJQ2 could return a
"template view".

If the resolver service was in biocode-fims-commons, this would be a
service that returned a response other then JSON, however it would use
templates which would be fully customizable on a per fims project basis. We
could also put the resolverService in each fims project that uses is,
however this seems like we would writing redundant code.

**Comment by jdeck88** [comment]
Yes, great to have a template response for:
http://www.biscicol.org/id/ark:/21547/AJQ2

and really do a redirect for:
http://biscicol.org/id/ark:/21547/R2MBIO56

Just as long as i don't have to look at JSON when these pages open!
John

On Sat, Feb 13, 2016 at 10:35 PM, RJ Ewing notifications@github.com wrote:

> I believe this is because we have the ResovlerService and the
> ResolverMetadataService. As well as those urls are the REST services vs the
> jsp pages.
> 
> I think it would work to consolidate the services and have one service that
> either returned the metadata or redirected the user to the speciman page.
> In that case, http://www.biscicol.org/id/ark:/21547/AJQ2 could return a
> "template view".
> 
> If the resolver service was in biocode-fims-commons, this would be a
> service that returned a response other then JSON, however it would use
> templates which would be fully customizable on a per fims project basis. We
> could also put the resolverService in each fims project that uses is,
> however this seems like we would writing redundant code.
> 
> On Fri, Feb 12, 2016 at 1:17 PM, John Deck notifications@github.com
> wrote:
> 
> > Oh, and one other issue... when linking from the the CDLIB site, what
> > gets
> > returned is JSON where it should be the metadata page:
> > 
> > E.g. look at a FIMS ID at CDL:
> > http://ezid.cdlib.org/id/ark:/21547/AJQ2
> > 
> > then you can click the link that feeds to BiSciCol:
> > 
> > http://www.biscicol.org/id/ark:/21547/AJQ2
> > 
> > And it returns JSON. IF you extract the address returned in the JSON it
> > is
> > a bit better:
> > 
> > http://www.biscicol.org/id/metadata/ark:/21547/AJQ2
> > 
> > But... it doesn't give you styling. However, if you use the key/value
> > method of calling it:
> > 
> > http://www.biscicol.org/lookup.jsp?id=ark:/21547/AJQ2
> > 
> > it gives the correct view.
> > 
> > So, the ideal situation would be to have
> > http://www.biscicol.org/id/ark:/21547/AJQ2 return the correct view from
> > the
> > start. Possible?
> > 
> > On Thu, Feb 11, 2016 at 9:10 PM, John Deck jdeck88@gmail.com wrote:
> > 
> > > ok-- that was one issue, and everything works, EXCEPT the sample on the
> > > page... just use the example in the text box that appears when you load
> > > the
> > > page and press the submit button.
> > > 
> > > John
> > > 
> > > On Thu, Feb 11, 2016 at 6:38 PM, RJ Ewing notifications@github.com
> > > wrote:
> > > 
> > > > I think the problem is the resolverMetadataPrefix setting. It should
> > > > be
> > > > http://www.biscicol.org/id/metadata/
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/biocodellc/biscicol-fims/issues/7#issuecomment-183153637
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > John Deck
> > > (541) 914-4739
> > 
> > ## 
> > 
> > John Deck
> > (541) 914-4739
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/biocodellc/biscicol-fims/issues/7#issuecomment-183182972
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biocodellc/biscicol-fims/issues/7#issuecomment-183831934
> .

## 

John Deck
(541) 914-4739

**Comment by rodney757** [comment]
okay, this has been implemented now. We are using a template for the metadata displays, and redirecting if the identifier contains a suffix.
