### ISSUE TITLE
displaying map on data load fails w/ fasta file specified.

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biscicol-fims#8]
The mapping file might be reading the wrong file when looking up coordinates using  biocode-fims-mapping.js 

I think it is this line and seems to just take the first file in array

```
  var inputFile= $('#' + datasetId)[0].files[0];
```

So, when TWO files are specified i think it is not knowing which one to choose.

**Comment by rodney757** [comment]
Hmm, datasetId is a global variable that should be dynamically set when parsing the file ext. I'll take a look

**Comment by rodney757** [comment]
fixed with commit 8557f6df03de2fa4d12b5f84afd6a5850469bc8f
